version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: random
    versions:
    - 3.0.0
    - 3.0.3
  - dependency-name: framer-motion
    versions:
    - 4.0.3
    - 4.1.2
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.2.2
  - dependency-name: i18next
    versions:
    - 19.9.0
    - 20.1.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@storybook/addons"
    versions:
    - 6.1.17
  - dependency-name: "@sentry/browser"
    versions:
    - 6.0.1
    - 6.0.3
  - dependency-name: "@commitlint/config-conventional"
    versions:
    - 12.0.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
  - dependency-name: semver
    versions:
    - 7.3.4
