name = "poi-web"
type = "javascript"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2022-01-23"
account_id = "2dc3483aa62d4b5dc774ec04713893de"

[site]
bucket = "packages/web/build"
entry-point = "packages/worker"

[build]
command = "yarn esbuild index.ts --bundle --outfile=dist/index.js"
cwd = "packages/worker"

[build.upload]
format = "service-worker"
