name = "poi-web"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
site = {bucket = "build",entry-point = "workers-site"}
compatibility_date = "2022-01-23"
account_id = "2dc3483aa62d4b5dc774ec04713893de"
