name: Gated

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Gated
    steps:
      - uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        name: Caching Node.js dependencies
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v1

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn workspaces run typecheck

      - name: Unit tests
        run: yarn workspace web test

      - name: Build Web
        run: yarn workspace web build

      - name: Build worker
        uses: poooi/wrangler-action@23e3ebb1486e79006f7b3c89cd87bff99c6d9b9c
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          publish: false
          preCommands: wrangler build
