name: Integration

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Integration
    steps:
      - uses: actions/checkout@v3

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v3.2.1
        name: Caching Node.js dependencies
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v2-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-v2

      - name: Yarn install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn workspace web build

      - name: E2E tests preparation
        run: |
          npm i -g wrangler
          yarn playwright install chromium --with-deps

      - name: E2E tests
        run: yarn test:integration
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}

